# Generated by Django 4.1.1 on 2022-11-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20)),
                ('Nickname', models.CharField(max_length=20)),
                ('Occupation', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=50)),
                ('Hobby', models.CharField(max_length=20)),
            ],
        ),
    ]
