# Generated by Django 4.1.1 on 2022-11-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Hobby',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Nickname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Occupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Username',
            new_name='username',
        ),
    ]
