# Generated by Django 4.1.1 on 2022-11-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_address_userinfo_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
