# Generated by Django 4.1.1 on 2022-11-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('hobby', models.CharField(max_length=20)),
            ],
        ),
    ]
