# Generated by Django 4.1.1 on 2022-11-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bloginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
