# Generated by Django 3.2.14 on 2022-12-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bloginfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='timeRecord',
            field=models.DateField(default=None),
        ),
    ]
