# Generated by Django 4.1.1 on 2022-12-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_bloginfo_timerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='timerecord',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
