# Generated by Django 3.2.14 on 2022-10-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
