# Generated by Django 3.2.14 on 2022-10-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_homework2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
            ],
        ),
    ]
