# Generated by Django 3.2.14 on 2022-10-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_simpleblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('finalgrade', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='simpleblog',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
